### ISSUE TITLE
Spurious Keycodes Prevent Hardware Keyboard from Functioning Properly

### ISSUE THREAD

**Issue by BlueNalgene** [Slimbook-Team/slimbook-qc71-dkms#4]
## Vitals
```
OS: Kubuntu 22.04.2 LTS x86_64 
Host: TITAN Standard 
Kernel: 5.15.0-73-generic 
Uptime: 17 hours, 34 mins 
Packages: 3125 (dpkg), 12 (flatpak), 12 (snap) 
Shell: bash 5.1.16 
Resolution: 3840x2160, 3840x2160, 2560x1440 
DE: Plasma 5.24.7 
WM: KWin 
Theme: [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
Terminal Font: Hack 12 
CPU: AMD Ryzen 9 5900HX with Radeon Graphics (16) @ 3.300GHz 
GPU: AMD ATI 06:00.0 Cezanne 
GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q 
Memory: 7649MiB / 31499MiB
```

## Problem

A program is issuing spurious key events.  Running two terminals at the same time, I ran ``xev`` in one and ``journalctl -f`` in the other.  The following are observed at the same time.

#### ``xev``

```
KeyPress event, serial 40, synthetic NO, window 0x3000001,
    root 0x279, subw 0x0, time 64945867, (167,-12), root:(8398,993),
    state 0x0, keycode 248 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x3000001,
    root 0x279, subw 0x0, time 64945867, (167,-12), root:(8398,993),
    state 0x0, keycode 248 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 41, synthetic NO, window 0x3000001,
    root 0x279, subw 0x0, time 64946895, (167,-12), root:(8398,993),
    state 0x0, keycode 248 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 41, synthetic NO, window 0x3000001,
    root 0x279, subw 0x0, time 64946895, (167,-12), root:(8398,993),
    state 0x0, keycode 248 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

#### ``journalctl -f``

```
Jun 13 14:05:03 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: qc71_wmi_event_handler(value=0xd2)
Jun 13 14:05:03 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: obj->type = 1
Jun 13 14:05:03 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: int = 188
Jun 13 14:05:03 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode
Jun 13 14:05:03 wes-TITAN python3[1975]: INFO-1   1
Jun 13 14:05:04 wes-TITAN rtkit-daemon[2396]: Supervising 14 threads of 8 processes of 1 users.
Jun 13 14:05:04 wes-TITAN rtkit-daemon[2396]: Supervising 14 threads of 8 processes of 1 users.
Jun 13 14:05:04 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: qc71_wmi_event_handler(value=0xd2)
Jun 13 14:05:04 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: obj->type = 1
Jun 13 14:05:04 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: int = 188
Jun 13 14:05:04 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode
```

It appears that something is logging events as ``qc71_wmi_event_handler`` with ``case 188`` at the same time as I see spurious keycode 248 calls.  I am posting this issue in the ``slimbook-qc71-dkms`` repo since it is the only one that issues case 188.

I checked the hardware buttons available to the ``QC71 laptop input device`` and the only event codes available are 229, 230, 240, 247, 465, 4, and 3.  There is no mention of keycode 248.  However, much like the ``xev`` and ``journalctl -f`` log, I see reports of keycode 240 pressed.

#### ``sudo evtest``

```
Input driver version is 1.0.1
Input device ID: bus 0x19 vendor 0x0 product 0x0 version 0x0
Input device name: "QC71 laptop input device"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 229 (KEY_KBDILLUMDOWN)
    Event code 230 (KEY_KBDILLUMUP)
    Event code 240 (KEY_UNKNOWN)
    Event code 247 (KEY_RFKILL)
    Event code 465 (KEY_FN_ESC)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
  Event type 5 (EV_SW)
    Event code 3 (SW_RFKILL_ALL) state 1
Properties:
Testing ... (interrupt to exit)
Event: time 1686683561.216977, type 4 (EV_MSC), code 4 (MSC_SCAN), value bc
Event: time 1686683561.216977, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 1
Event: time 1686683561.216977, -------------- SYN_REPORT ------------
Event: time 1686683561.216981, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 0
Event: time 1686683561.216981, -------------- SYN_REPORT ------------
Event: time 1686683562.280406, type 4 (EV_MSC), code 4 (MSC_SCAN), value bc
Event: time 1686683562.280406, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 1
Event: time 1686683562.280406, -------------- SYN_REPORT ------------
Event: time 1686683562.280418, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 0
Event: time 1686683562.280418, -------------- SYN_REPORT ------------
Event: time 1686683575.568774, type 4 (EV_MSC), code 4 (MSC_SCAN), value bc
Event: time 1686683575.568774, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 1
Event: time 1686683575.568774, -------------- SYN_REPORT ------------
Event: time 1686683575.568782, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 0
Event: time 1686683575.568782, -------------- SYN_REPORT ------------
Event: time 1686683576.608433, type 4 (EV_MSC), code 4 (MSC_SCAN), value bc
Event: time 1686683576.608433, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 1
Event: time 1686683576.608433, -------------- SYN_REPORT ------------
Event: time 1686683576.608444, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 0
Event: time 1686683576.608444, -------------- SYN_REPORT ------------
```

## Why does this matter?

This keypress occurs roughly every few seconds on my system.  However, since the action is observed by ``X`` as keypress and keyrelease events which have ``XFilterEvent returns: False`` flag, the event occurs without filtering on all programs.  At the user level, this means that any key pressed during that event is blocked.  This means I can't hold down keys like the arrow keys or backspace without the keypress stopping every few seconds.  I originally reported this as a hardware bug in email (to Alex on April 22, 2022) as a potential problem with switch debounce or rollover, but it has become clear that the issue is more complicated and rooted in the qc71 device.

## Attempts to remedy:

- closing slimbookamdcontroller in the taskbar -- no change
- ``sudo killall python3`` -- restarts the slimbook.service device detection, but does not change keypresses
- Disable slimbook autostart using Slimbook Client Autostart preferences (https://slimbook.es/en/forum/question/7776-notificaciones-de-slimbook-service) -- This does not work because the autostart setting does not appear to persist on restart.

## What is needed

I need:
1. A way to properly kill the slimbook.service if I want to.
2. Whichever slimbook process is sending real key events to stop so I can type.

**Comment by Lt-Henry** [comment]
As I am one of the co-authors of this slimbook tuned qc71 driver, I think I can shed some light here. 

It looks like event 188 is pushing down a key event. As there is no key mapped to this event, function sparse_keymap_report_event is pushing a KEY_UNKNOWN (240) as default. Just what evtest shows. I don't understand why, but it looks like Xlib translates that 240 to 248. There is some keycode-keysym logic I am too tired to figured it out.

Would be nice to check why perf mode is triggered every second, but I think a healthy driver should deal with this.

I can provide a patch for this, It may not be too difficult.

**Comment by BlueNalgene** [comment]
@Lt-Henry 
 
> Would be nice to check why perf mode is triggered every second

If I can pull some specific log files or values that would help diagnosing the "why" of the errors in addition to patching the behavior, let me know what you need.

> I can provide a patch for this, It may not be too difficult.

Hooray!

**Comment by Lt-Henry** [comment]
Can you please check this branch out and test? I won't have access to a qc71 based slimbook for a while.

https://github.com/Lt-Henry/slimbook-qc71-dkms/tree/fix_issue_4

After some days reading the code, I am afraid this problem is also present on more WMI events, even on original source. So, if this works, I would submit a complete fix for both this and original Barnabas driver.

**Comment by BlueNalgene** [comment]
Thanks for the fork, @Lt-Henry .  I'm not sure what the make pipeline is for this package since the documentation is sparse, so I've had to guess.  What I've done is:

```
sudo apt remove slimbook-qc71-dkms
git clone https://github.com/Lt-Henry/slimbook-qc71-dkms.git && cd slimbook-qc71-dkms
sudo make install
```

which reports:

```
install -d "/usr/share/-dkms"
install -m 755 /usr/lib/dkms/common.postinst /usr/share/-dkms/postinst
```

But this only copies the ``postinst`` file over.  I can't ``modprobe``.  What do I need to do next?

I tried to enter ``qc71_laptop`` and make things from there, but I get various errors:

```
$ sudo make dkmsinstall
mkdir -p /usr/src/qc71_laptop-0.0
cp Makefile dkms.conf battery.c debugfs.c ec.c events.c fan.c features.c hwmon.c hwmon_fan.c hwmon_pwm.c led_lightbar.c main.c misc.c pdev.c battery.h debugfs.h ec.h events.h fan.h features.h hwmon_fan.h hwmon.h hwmon_pwm.h led_lightbar.h misc.h pdev.h pr.h util.h wmi.h /usr/src/qc71_laptop-0.0/.
dkms add qc71_laptop/0.0
Error! DKMS tree already contains: qc71_laptop-0.0
You cannot add the same module/version combo more than once.
make: *** [Makefile:33: dkmsinstall] Error 3
```

What should I be doing?

**Comment by Lt-Henry** [comment]
Try `sudo make dkmsuninstall` and then `sudo make dkmsinstall`

Perhaps, would be a good thing if dkmsinstall already handles this.

**Comment by BlueNalgene** [comment]
I tried that in a few places:

### In /slimbook-qc71-dkms

The top level Makefile does not have the appropriate build commands.

```
$ sudo make dkmsuninstall
[sudo] password for wes: 
make: *** No rule to make target 'dkmsuninstall'.  Stop.
```

```
sudo make dkmsinstall
make: *** No rule to make target 'dkmsinstall'.  Stop.
```

### In /slimbook-qc71-dkms/slimbook-qc71

There is nothing in my modules that has the correct name.

```
sudo make dkmsuninstall
rmmod qc71_laptop
rmmod: ERROR: Module qc71_laptop is not currently loaded
make: [Makefile:38: dkmsuninstall] Error 1 (ignored)
dkms uninstall qc71_laptop/0.0
Error! The module/version combo: qc71_laptop-0.0 is not located in the DKMS tree.
make: [Makefile:39: dkmsuninstall] Error 3 (ignored)
dkms remove qc71_laptop/0.0 --all
Error! The module/version combo: qc71_laptop-0.0 is not located in the DKMS tree.
make: [Makefile:40: dkmsuninstall] Error 3 (ignored)
rm -rf /usr/src/qc71_laptop-0.0
```

And the correct binary is not found for my kernel
```
$ sudo make dkmsinstall
mkdir -p /usr/src/qc71_laptop-0.0
cp Makefile dkms.conf battery.c debugfs.c ec.c events.c fan.c features.c hwmon.c hwmon_fan.c hwmon_pwm.c led_lightbar.c main.c misc.c pdev.c battery.h debugfs.h ec.h events.h fan.h features.h hwmon_fan.h hwmon.h hwmon_pwm.h led_lightbar.h misc.h pdev.h pr.h util.h wmi.h /usr/src/qc71_laptop-0.0/.
dkms add qc71_laptop/0.0
Creating symlink /var/lib/dkms/qc71_laptop/0.0/source -> /usr/src/qc71_laptop-0.0
dkms build qc71_laptop/0.0

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j16 KERNELRELEASE=5.15.0-78-generic KDIR=/lib/modules/5.15.0-78-generic/build...(bad exit status: 2)
ERROR (dkms apport): binary package for qc71_laptop: 0.0 not found
Error! Bad return status for module build on kernel: 5.15.0-78-generic (x86_64)
Consult /var/lib/dkms/qc71_laptop/0.0/build/make.log for more information.
make: *** [Makefile:34: dkmsinstall] Error 10
```

I can confirm that nothing is installed for my modprobe with a find command elsewhere in my history, but can you tell me what kernel you compiled this for?

### In /qc71_laptop

Interestingly, if I compile from the upstream pobrn package (without Slimbook modification), I get different results.  Note, I actually ran these commands in the opposite order to get this output, but I kept the same uninstall->install format here for consistency.

```
$ sudo make dkmsuninstall
rmmod qc71_laptop
rmmod: ERROR: Module qc71_laptop is not currently loaded
make: [Makefile:38: dkmsuninstall] Error 1 (ignored)
dkms uninstall qc71_laptop/0.0
Module qc71_laptop-0.0 for kernel 5.15.0-78-generic (x86_64).
Before uninstall, this module version was ACTIVE on this kernel.

qc71_laptop.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.15.0-78-generic/updates/dkms/
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...
make: [Makefile:39: dkmsuninstall] Error 1 (ignored)
dkms remove qc71_laptop/0.0 --all
Module qc71_laptop-0.0 for kernel 5.15.0-78-generic (x86_64).
This module version was INACTIVE for this kernel.
depmod...
Deleting module qc71_laptop-0.0 completely from the DKMS tree.
rm -rf /usr/src/qc71_laptop-0.0

```

This actually removes my old version correctly.  I can confirm with ``xev`` that the spurious keycode symptom is gone and my laptop actually sleeps correctly.  But this does not solve the problem for this package.

```
$ sudo make dkmsinstall
mkdir -p /usr/src/qc71_laptop-0.0
cp Makefile dkms.conf battery.c debugfs.c ec.c events.c fan.c features.c hwmon.c hwmon_fan.c hwmon_pwm.c led_lightbar.c main.c misc.c pdev.c battery.h debugfs.h ec.h events.h fan.h features.h hwmon_fan.h hwmon.h hwmon_pwm.h led_lightbar.h misc.h pdev.h pr.h util.h wmi.h /usr/src/qc71_laptop-0.0/.
dkms add qc71_laptop/0.0
Creating symlink /var/lib/dkms/qc71_laptop/0.0/source -> /usr/src/qc71_laptop-0.0
dkms build qc71_laptop/0.0

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j16 KERNELRELEASE=5.15.0-78-generic KDIR=/lib/modules/5.15.0-78-generic/build...
Signing module:
 - /var/lib/dkms/qc71_laptop/0.0/5.15.0-78-generic/x86_64/module/qc71_laptop.ko
Secure Boot not enabled on this system.
cleaning build area...
dkms install qc71_laptop/0.0

qc71_laptop.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/5.15.0-78-generic/updates/dkms/

depmod...
```

This works to install the upstream driver.  Something is missing in the Makefile for this package.

**Comment by Lt-Henry** [comment]
Driver was patched for kernels 6.x and stopped working on 5.x. If you pull again my branch, I have fixed this so it must work with any kernel. Upstream driver already fixed that, we have to re-sync for last commits.

> I can confirm with xev that the spurious keycode symptom is gone and my laptop actually sleeps correctly

I think upstream driver also suffers from this issue, but the event that causes your problem is not handled by upstream driver.

So, do you have problems also sleeping the laptop with slimbook-qc71 module?

**Comment by BlueNalgene** [comment]
Apologies for disappearing for a few weeks.  I was doing field work in the desert, and I did not have the internet capacity to engage on this (maximum of 2 Mbps down!).  

> So, do you have problems also sleeping the laptop with slimbook-qc71 module?

Yes, the slimbook-qc71 module seemed to prevent sleeping.  This was presumably due to the constant 188 codes which made the computer detect input.

==================

I still don't know how to make and install this branch from source.  Do you have a compile method you can tell me?

**Comment by Lt-Henry** [comment]
No need to apologize  :D

We submitted a pull request to original qc71 driver as we are trying to keep up to date with it. He haven't accepted yet, but maybe he wants to push events to user space using "fake" keystrokes. Meanwhile, we will have to wait and see what happens with the PR.

Give me a couple of days and I will provide you with a patched debian package to test. 

Using keystrokes or not, driver shouldn't be emitting 188 events (performance mode changed) constantly.

Can you please provide us a `dmidecode -t bios` output? So we can check bios and firmware versions.

**Comment by BlueNalgene** [comment]
Hooray for upstream problems!

```
$ sudo dmidecode -t bios
# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 3.3.0 present.

Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
        Vendor: American Megatrends International, LLC.
        Version: N.1.24GRU05
        Release Date: 08/31/2021
        Address: 0xF0000
        Runtime Size: 64 kB
        ROM Size: 16 MB
        Characteristics:
                PCI is supported
                BIOS is upgradeable
                BIOS shadowing is allowed
                Boot from CD is supported
                Selectable boot is supported
                BIOS ROM is socketed
                EDD is supported
                Japanese floppy for NEC 9800 1.2 MB is supported (int 13h)
                Japanese floppy for Toshiba 1.2 MB is supported (int 13h)
                5.25"/360 kB floppy services are supported (int 13h)
                5.25"/1.2 MB floppy services are supported (int 13h)
                3.5"/720 kB floppy services are supported (int 13h)
                3.5"/2.88 MB floppy services are supported (int 13h)
                Print screen service is supported (int 5h)
                8042 keyboard services are supported (int 9h)
                Serial services are supported (int 14h)
                Printer services are supported (int 17h)
                CGA/mono video services are supported (int 10h)
                ACPI is supported
                USB legacy is supported
                BIOS boot specification is supported
                Targeted content distribution is supported
                UEFI is supported
        BIOS Revision: 5.19
        Firmware Revision: 1.30

Handle 0x0007, DMI type 13, 22 bytes
BIOS Language Information
        Language Description Format: Long
        Installable Languages: 1
                en|US|iso8859-1
        Currently Installed Language: en|US|iso8859-1
```

**Comment by Lt-Henry** [comment]
Sorry, It took me longer than I thought.

Any way, I've uploaded a 0.2.5-noreport_188 debian package at releases, here on github. It won't generate a keystroke on every 188 event and it will log perfomance status, so it may help us tracking this problem.

On the other, is your Titan de THX one? Have you ever upgraded Bios and/or EC?

**Comment by BlueNalgene** [comment]
No need to apologize.  I was the one that was in the desert for over a month.

I'm not sure what you mean by Titan THX.  Do you mean RTX?  If so, then yes, it is running the NVIDIA RTX 3070 wity the Ryzen 9 CPU.  I have not upgraded the bios, however I have had to swap the primary drives as the SSD had a complete hardware failure.  The bios and EC should be stock which shipped from Slimbook in March/April 2022.  

=========================================

Testing the .deb file

|                      Type                      | Does xev report spurious keycodes? | Does the system suspend properly? |
|:----------------------------------------------:|:----------------------------------:|:---------------------------------:|
|                      None                      |                 No                 |                Yes                |
|       slimbook-qc71-dkms_0.2.5_amd64.deb       |                 No                 |                Yes                |
| slimbook-qc71-dkms_0.2.5.noreport188_amd64.deb |                 No                 |                Yes                |

Everything looks like it is functioning correctly.  The fix may have occurred upstream though, since I cannot tell the difference between the noreport188 version and the original.  Should we close this issue as solved?

**Comment by Lt-Henry** [comment]
To be honest, I still don't understand why your system generated a performance event change almost every second. It has no sense to me from software side. I will keep my eyes open.

> I cannot tell the difference between the noreport188 version and the original

noreport188 just doesn't produce a keystroke on 188 events (performance mode changed) preventing system to suspend and messing keyboard usage. 

> Should we close this issue as solved?

Yeah, I am going to close it but we can open it again if the issue comes back. 

Thanks for your excellent work reporting the issue!

**Comment by BlueNalgene** [comment]
I agree, it doesn't really make sense why it happened.  I wonder if something else was triggering the mode flip repeatedly which was removed when I uninstalled dkms.  

> noreport188 just doesn't produce a keystroke 

I understand what the intention was, but I cannot replicate a 188 keystroke on the original version.  Hence, I cannot observe the difference on my machine based on behavior.  But hey, as long as things were solved, I'm happy.

Thank you as well for your diligent work on this mystery.

**Comment by BlueNalgene** [comment]
Bonus information: I accidentally installed ''slimbook-qc71-dkms v0.2.5'' from apt which replaced ''v0.2.5~noreport188''and the problem re-emerged.  I noticed that the system did not suspend properly, so I checked ``xev`` and noticed the extra keycodes.  This means that while I was not able to recreate the issue in the table I posted 2 weeks ago, the problem came back from the apt package.  I believe the apt build may have something funny in it.  

Either way, the ~noreport188 version fixes the problem.  I recommend a PR be submitted to fix this on the ppa.

**Comment by Lt-Henry** [comment]
Yes, we want to get rid off keystroke events, including 188 one. But currently some of them are needed by slimbook-service in order to receive performance change notifications. But we are already working on it.

On the other hand, I can only explain your issue if there is some sort of firmware bug. noreport188 just ignored the event, but it was still there... every second?

Can you please look at journal log and look for "change perf mode" strings? We are curious about what firmware is doing.

**Comment by BlueNalgene** [comment]
The perf mode is still triggered roughly every second that the computer is awake.  Posting the full log here, so here is a summary.  

Since I posted 5 days ago (using noreport188):
```
$ journalctl --since="5 days ago" | grep -c "change perf mode" 
41117
```

In the 5 days prior to that (using apt package for a few days of it)
```
$ journalctl --since="10 days ago" --until="5 days ago" | grep -c "change perf mode" 
17640
```

Digging into my apt history, my accidental upgrade to the apt version was at 2023-10-05 T11:00:07 and I  did more testing to confirm it was the apt package causing the sleep issues during an upgrade at 2023-10-06 T02:43:22.  Something interesting happens here.

When I transition from ~noreport188 to aptversion, the system journal changes:

```
Oct 04 15:35:24 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 05 11:05:25 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode
```

The noreport version adds a "0" to the log lines.  This continues several thousand times.  

Here is a sample of the latest logs when I queried journalctl:

```
$ journalctl --since="5 minutes ago" | grep "change perf mode" 
Oct 11 13:05:37 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:05:38 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:05:40 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:05:41 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:05:53 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:05:54 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:05:56 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:05:57 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:06:02 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:06:03 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:07:44 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:07:45 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:07:46 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:07:50 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:07:51 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:07:53 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:07:54 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:07:56 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:07:57 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:05 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:06 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:08 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:09 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:11 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:12 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:14 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:15 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:25 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:26 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:31 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:32 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:33 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:34 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:36 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:08:37 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:09:15 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:09:16 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:09:18 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:09:19 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:09:35 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:09:36 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:09:38 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:09:39 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:09:41 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:09:42 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:09:59 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:10:00 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:10:19 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:10:20 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:10:22 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:10:23 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:10:24 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:10:25 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:10:26 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
```

And here is a shorter time scale with a few lines of context surrounding the events:

```
$ journalctl --since="1 minute ago" | grep -B 5 -A 5 "change perf mode" 
Oct 11 13:11:06 wes-TITAN rtkit-daemon[2310]: Supervising 9 threads of 6 processes of 1 users.
Oct 11 13:11:06 wes-TITAN rtkit-daemon[2310]: Supervising 9 threads of 6 processes of 1 users.
Oct 11 13:11:07 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: qc71_wmi_event_handler(value=0xd2)
Oct 11 13:11:07 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: obj->type = 1
Oct 11 13:11:07 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: int = 188
Oct 11 13:11:07 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:11:08 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: qc71_wmi_event_handler(value=0xd2)
Oct 11 13:11:08 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: obj->type = 1
Oct 11 13:11:08 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: int = 188
Oct 11 13:11:08 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:11:10 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: qc71_wmi_event_handler(value=0xd2)
Oct 11 13:11:10 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: obj->type = 1
Oct 11 13:11:10 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: int = 188
Oct 11 13:11:10 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:11:11 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: qc71_wmi_event_handler(value=0xd2)
Oct 11 13:11:11 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: obj->type = 1
Oct 11 13:11:11 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: int = 188
Oct 11 13:11:11 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:11:20 wes-TITAN rtkit-daemon[2310]: Supervising 9 threads of 6 processes of 1 users.
Oct 11 13:11:20 wes-TITAN rtkit-daemon[2310]: Supervising 9 threads of 6 processes of 1 users.
Oct 11 13:11:23 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: qc71_wmi_event_handler(value=0xd2)
Oct 11 13:11:23 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: obj->type = 1
Oct 11 13:11:23 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: int = 188
Oct 11 13:11:23 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:11:24 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: qc71_wmi_event_handler(value=0xd2)
Oct 11 13:11:24 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: obj->type = 1
Oct 11 13:11:24 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_handler: int = 188
Oct 11 13:11:24 wes-TITAN kernel: qc71_laptop/events: qc71_wmi_event_d2_handler: change perf mode 0
Oct 11 13:11:34 wes-TITAN rtkit-daemon[2310]: Supervising 9 threads of 6 processes of 1 users.
Oct 11 13:11:34 wes-TITAN rtkit-daemon[2310]: Supervising 9 threads of 6 processes of 1 users.
```

Since I'm still seeing an event 188 in the logs, but I'm not seeing the effects on my computer suspend, I want to confirm everything is working correctly.

```
$ dkms status -m slimbook-qc71 
slimbook-qc71/0.0, 5.15.0-86-generic, x86_64: installed
```

This seems like an incorrect version number.  But according to my bash history, the last line that comes up when I ``grep slimbook`` is:

```
sudo dpkg -i slimbook-qc71-dkms_0.2.5.noreport188_amd64.deb
```

So the current version should be noreport188.  Perhaps the experimental version did not update the version number to be visible to DKMS?

**Comment by Lt-Henry** [comment]
The 0.0 version path is not an issue at all. We will fix it some day but it is only useful if you want to keep several versions, and we don't.

For a moment, we thought your laptop had the performance switch stuck. But your log reveals performance events with no change at all, which makes no sense. So, the most plausible option we have right now, it is some sort of Firmware bug, either Bios or EC.

Anyway, we are going to release a new version this month and I will remove 188 keystrokes definitely.
